server:
  port: 8081
logging:
  level:
    org.springframework: DEBUG

spring:
  application:
    name:"login-service-demo"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
#    for localhost
    url: "jdbc:postgresql://localhost:5432/moves?createDatabaseIfNotExist=true"
    username: demo
    password: demo
#    url: "jdbc:postgresql://db:5432/moves?createDatabaseIfNotExist=true"
#    username: abc
#    password: abc
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
